---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: zooma
    password: zooma
    email: hazem.soussi@esprit.tn
- name: Push to docker hub
  docker_image:
    name: hazem1998/livraison
    repository: hazem1998/livraison
    tag: latest
    source: local
    push: yes
